<?php
/**
 * @package     Plumrocket_AmpEmail
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

/** @var \Plumrocket\AmpEmail\Block\Component\State\Cart $block */
?>
<amp-state id="<?= $block->escapeHtmlAttr($block->getStateId()) ?>">
    <script type="application/json">
        {
            "status" : {},
            "id" : "<?= $block->escapeHtml($block->getIdPrefix()) ?>0"
        }
    </script>
</amp-state>

<form id="atc_form"
      method="POST"
      action-xhr="<?= $block->escapeUrl($block->getAddToCartUrl()) ?>"
      on="submit-success: AMP.setState({<?= $block->escapeHtmlAttr($block->getStateId()) ?>: {status: {[<?= $block->escapeHtmlAttr($block->getStateId()) ?>.id]: 1} } });submit-error: AMP.setState({<?= $block->escapeHtmlAttr($block->getStateId()) ?>: {status: {[<?= $block->escapeHtmlAttr($block->getStateId()) ?>.id]: 0} } })"
>
    <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($block->getIdPrefix()) ?>0" [value]="<?= $block->escapeHtmlAttr($block->getStateId()) ?>.id"/>
</form>