<?php
/**
 * @package     Plumrocket_AmpEmail
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<amp-state id="<?= $block->escapeHtmlAttr($block->getStateId()) ?>">
    <script type="application/json">
        {
            "id" : "",
            "code" : "",
            "confirm": {
                "form_status": ""
            }
        }
    </script>
</amp-state>