#!/usr/bin/env bash
#
# STEP 7 of the Magento 2.4.6 -> 2.4.9 upgrade: SCHEMA, DATA AND SEARCH
#
#   bash shell/07-magento-upgrade.sh
#
# Runs after shell/06-composer-upgrade.sh has put 2.4.9 code on disk.
# This is the step that rewrites the database schema against live data
# (10,470 orders / 5,003 customers), so it refuses to start without a backup.
#
# Ends by taking the site OUT of maintenance mode.
#
# Idempotent: every command here is safe to re-run. If it fails part way,
# fix the cause and run it again from the top.
#
set -euo pipefail

MAGENTO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKUP_ROOT="/var/backups/marytylor-2.4.9"
TARGET="2.4.9"
LOCALES="en_US"
OS_HOST="127.0.0.1"
OS_PORT="9200"

log()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
ok()   { printf '    \033[0;32m[ok]\033[0m %s\n' "$*"; }
warn() { printf '    \033[0;33m[warn]\033[0m %s\n' "$*"; }
die()  { printf '\n\033[0;31m[FATAL]\033[0m %s\n' "$*" >&2; exit 1; }

cd "$MAGENTO_ROOT"

# ---------------------------------------------------------------------- guards
log "Pre-flight checks"

# Running this under sudo is what left pub/static owned root:root last time,
# which then breaks every later deploy run as the normal user.
[[ "$(id -u)" -ne 0 ]] || die "do not run this as root -- it would leave pub/static and generated/ owned by root.
       Run it as the web/CLI user (payless)."
ok "running as $(whoami), not root"

INSTALLED="$(php -r '
    $f = "vendor/composer/installed.json";
    if (!is_file($f)) { echo "none"; exit; }
    $j = json_decode(file_get_contents($f), true);
    foreach (($j["packages"] ?? $j) as $p) {
        if ($p["name"] === "magento/product-community-edition") { echo $p["version"]; exit; }
    }
    echo "none";
')"
[[ "$INSTALLED" == "$TARGET" ]] \
    || die "vendor/ holds magento ${INSTALLED}, not ${TARGET}. Run shell/06-composer-upgrade.sh first."
ok "magento/product-community-edition ${INSTALLED} on disk"

shopt -s nullglob
BACKUPS=("${BACKUP_ROOT}"/*/)
shopt -u nullglob
[[ ${#BACKUPS[@]} -gt 0 ]] \
    || die "no backup found in ${BACKUP_ROOT} -- this step rewrites the schema. Run: sudo bash shell/03-backup.sh"
ok "backup present: ${BACKUPS[-1]}"

# OpenSearch must answer before we point Magento at it and reindex.
OS_HEALTH="$(curl -fsS -m 10 "http://${OS_HOST}:${OS_PORT}/_cluster/health" 2>/dev/null || true)"
[[ -n "$OS_HEALTH" ]] \
    || die "OpenSearch is not answering on ${OS_HOST}:${OS_PORT}. Start it before running this step:
       sudo systemctl start opensearch"
OS_STATUS="$(printf '%s' "$OS_HEALTH" | php -r 'echo json_decode(stream_get_contents(STDIN), true)["status"] ?? "unknown";')"
case "$OS_STATUS" in
    green|yellow) ok "OpenSearch cluster status: ${OS_STATUS}" ;;
    *) die "OpenSearch cluster status is '${OS_STATUS}' -- fix before reindexing" ;;
esac

# ----------------------------------------------------------------- maintenance
log "Maintenance mode"
php bin/magento maintenance:enable
ok "maintenance mode ON"

# --------------------------------------------------------- schema + data upgrade
# NOTE: deliberately NOT --keep-generated, which doc/02-upgrade-plan.md called for.
# generated/ currently holds interceptors compiled against 2.4.6; keeping them
# against 2.4.9 code produces fatal errors. setup:upgrade clears them and
# setup:di:compile below rebuilds them.
log "Schema and data upgrade (rewrites the database -- the slow part)"
php bin/magento setup:upgrade

log "Confirming the schema is current"
php bin/magento setup:db:status

# ------------------------------------------------------------ search cutover
# Must happen BEFORE reindexing, or catalogsearch_fulltext indexes into the
# wrong engine. This site has never had a catalog/search/engine row -- it has
# been running on the 2.4.6 default (elasticsearch7) against a stopped server.
# config:set is idempotent, so this block is safe to re-run.
log "Pointing catalogue search at OpenSearch"
php bin/magento config:set catalog/search/engine opensearch
php bin/magento config:set catalog/search/opensearch_server_hostname "$OS_HOST"
php bin/magento config:set catalog/search/opensearch_server_port "$OS_PORT"
php bin/magento config:set catalog/search/opensearch_index_prefix magento2
php bin/magento config:set catalog/search/opensearch_enable_auth 0
php bin/magento config:set catalog/search/opensearch_server_timeout 15
ok "catalog/search/engine = opensearch @ ${OS_HOST}:${OS_PORT}"

# ------------------------------------------------------------------- compile
log "Compiling dependency injection"
php bin/magento setup:di:compile

log "Deploying static content (${LOCALES})"
php bin/magento setup:static-content:deploy -f $LOCALES

# pub/static/.htaccess strips the version segment from cache-busted asset URLs.
# It ships in the distribution, is NOT regenerated by static-content:deploy, and
# is not in this repo's git index -- so anything that clears pub/static drops it
# and the whole storefront loads unstyled. See doc/00-local-environment-setup.md.
log "Restoring pub/static/.htaccess"
if [[ ! -f pub/static/.htaccess ]]; then
    cp vendor/magento/magento2-base/pub/static/.htaccess pub/static/.htaccess \
        && ok "restored pub/static/.htaccess (was missing)"
else
    ok "pub/static/.htaccess present"
fi

# ------------------------------------------------------------------- reindex
log "Flushing cache before reindex"
php bin/magento cache:flush

log "Reindexing (catalogsearch_fulltext now writes to OpenSearch)"
php bin/magento indexer:reindex

log "Final cache flush"
php bin/magento cache:flush

# -------------------------------------------------------------- verification
log "Verification"
php bin/magento --version
php bin/magento setup:db:status
php bin/magento indexer:status

OS_INDICES="$(curl -fsS -m 10 "http://${OS_HOST}:${OS_PORT}/_cat/indices?h=index,docs.count" 2>/dev/null | grep -c magento2 || true)"
[[ "$OS_INDICES" -gt 0 ]] \
    && ok "OpenSearch holds ${OS_INDICES} magento2 index/indices" \
    || warn "no magento2 index in OpenSearch -- check var/log/exception.log"

log "Leaving maintenance mode"
php bin/magento maintenance:disable
ok "maintenance mode OFF"

# ------------------------------------------------------------------ smoke test
log "Smoke test"
CODE="$(curl -s -o /dev/null -w '%{http_code}' -m 30 -H 'Host: marytailor.local' http://127.0.0.1/ || echo 000)"
[[ "$CODE" == "200" ]] && ok "storefront returns 200" || warn "storefront returned ${CODE} -- check var/log/exception.log"

cat <<SUMMARY

    Upgrade complete on disk and in the database.

    Still to verify by hand -- see doc/02-upgrade-plan.md stage 7:
      - full checkout through to order placement
      - Rootways/Authorizecim against the gateway sandbox (payment module)
      - admin login, order grid, product save
      - catalogue search returns results
      - Hyva theme intact: logo and top menu
      - tail -f var/log/exception.log var/log/system.log

SUMMARY
