<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Media;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$mediaUrl = $viewModels->require(Media::class)->getMediaUrl();

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="w-full mx-auto">
    <div class="mb-10 md:pt-20 pt-0">
        <h2
            class="text-xl font-semibold tracking-widest text-gray-900 uppercase title-font text-center"
            id="footer-newsletter-heading"
        >
            <?= $escaper->escapeHtml(__('Subscribe Newsletter.')) ?>
        </h2>
        <p class="text-gray-700 text-xs pl-px text-center">
            <?= $escaper->escapeHtml(__('Get e-mail updates about our latest shop and special offers.')) ?>
        </p>
    </div>
    <form
        class="form subscribe"
        action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        x-data="initNewsletterForm()"
        @submit.prevent="submitForm()"
        id="newsletter-validate-detail"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Subscribe to Newsletter')) ?>"
    >

        <div class="flex w-full md:w-1/2 mx-auto justify-center gap-2 md:justify-start border h-[50px] relative shadow-[0_1px_0px_0px_#fff] pl-2.5 pr-[180px] rounded-[30px] border-solid border-neutral-200">
            <label for="newsletter-subscribe" class="sr-only">
                <?= $escaper->escapeHtml(__('Email Address')) ?>
            </label>
            <input
                name="email"
                type="email"
                required
                id="newsletter-subscribe"
                class="form-input w-full h-full text-sm text-neutral-500 shadow-none bg-transparent border-0 focus:border-0"
                placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your email address')) ?>"
                aria-describedby="footer-newsletter-heading"
            >
            <?= $block->getBlockHtml('formkey') ?>
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <button class="inline-flex shrink-0 ml-auto xl:mt-0 btn btn-primary absolute text-white h-full uppercase text-[13px] font-medium px-10 py-0 rounded-[30px] border-0 right-0 top-0">
                <?= $escaper->escapeHtml(__('Subscribe')) ?>
            </button>
        </div>
        <div>
            <template x-if="displayErrorMessage">
                <p class="flex items-center text-red">
                    <span class="inline-block w-8 h-8 mr-3">
                        <?= $heroicons->exclamationCircleHtml(); ?>
                    </span>
                    <template x-for="errorMessage in errorMessages">
                        <span x-html="errorMessage"></span>
                    </template>
                </p>
            </template>
        </div>
    </form>
    <div class="w-full">
        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div>
    <ul class="inline-block text-center w-full mt-10">
        <li class="inline-block px-4"><a class="social twitter fa fa-twitter" title="Twitter" href="https://twitter.com/marytylornatura"></a></li>
        <li class="inline-block px-4"><a class="social google fa fa-pinterest-p" title="Google" href="https://www.pinterest.com/marytylor/"></a></li>
        <li class="inline-block px-4"><a class="social facebook fa fa-facebook" title="Facebook" href="https://www.facebook.com/marytylornaturals/?ref=bookmarks"></a></li>
        <li class="inline-block px-4"><a class="social youtube fa fa-youtube" title="Youtube" href="https://www.youtube.com/channel/UCLkpVg9H2XS6OqbE3jcm-Ig/videos"></a></li>
        <li class="inline-block px-4"><a class="social youtube fa fa-instagram" title="Instagram" href="https://www.instagram.com/marytylornaturals/"></a></li>
    </ul>


    <div class="my-10 w-full md:w-5/6 mx-auto">
        <div class="flex flex-wrap border-b-neutral-200 border-b border-t-neutral-200 border-t border-solid ">
            <div class="w-full md:w-1/3 px-4 box1">
                <div class="relative px-0 py-8">
                    <div class="float-left w-3/12 h-full">
                        <img class="mx-auto" src="<?= $escaper->escapeUrl($mediaUrl . 'wysiwyg/bg_icon1.png') ?>" alt="Free delivery icon">
                    </div>
                    <div class="border-r-neutral-200 border-r border-solid">
                        <h2 class="text-xl font-bold">Free delivery</h2>
                        <p>Nam liber tempor cum soluta nobis eleifend option congue.</p>
                    </div>
                </div>
            </div>
            <div class="w-full md:w-1/3 px-4 box2">
                <div class="relative px-0 py-8">
                    <div class="float-left w-3/12 h-full">
                        <img class="mx-auto" src="<?= $escaper->escapeUrl($mediaUrl . 'wysiwyg/bg_icon2.png') ?>" alt="Money guarantee icon">
                    </div>
                    <div class="border-r-neutral-200 border-r border-solid">
                        <h2 class="text-xl font-bold">Money guarantee</h2>
                        <p>Claritas est etiam processus dynamicus, sequitur mutationem.</p>
                    </div>
                </div>
            </div>
            <div class="w-full md:w-1/3 px-4 box3">
                <div class="relative px-0 py-8">
                    <div class="float-left w-3/12 h-full">
                        <img class="mx-auto" src="<?= $escaper->escapeUrl($mediaUrl . 'wysiwyg/bg_icon3.png') ?>" alt="Online support icon">
                    </div>
                    <div class="text">
                        <h2 class="text-xl font-bold">Online support</h2>
                        <p>Nam liber tempor cum soluta nobis eleifend option congue.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>
