<?php

/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */
/**
 * @var $block \Mageside\Recipe\Block\Frontend\Recipe\RecipeList
 */
$config = $this->helper(\Mageside\Recipe\Helper\Config::class);
?>
<?php if ($config->getShowOnProductPage() && $block->getCollectionSize()) : ?>
    <div class="container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-b-2
                    border-gray-300 md:flex-row" bis_skin_checked="1">
        <h2 class="text-2xl font-medium text-gray-900 title-font">
            <?= $config->getProductBlockTitle(); ?> </h2>
    </div>

    <?= $block->getChildHtml('recipe_list'); ?>
<?php endif; ?>