<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<input type="hidden" name="category_products" id="in_category_products"
data-form-part="dolphin_productfaq_productfaq_form" value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Dolphin_Productfaq/products/assign-products": {
                "selectedProducts": <?= /* @noEscape */  $block->getProductsJson(); ?>,
                "gridJsObjectName": <?= /* @noEscape */  '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
