<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="text-gray-700 bg-[url('https://marytylor.com/cdn-cgi/image/quality=50/media/wysiwyg/bg-footer.jpg')] bg-cover mt-7" >
    <div class="container py-8 mx-auto">
        <div class="flex flex-wrap order-first gap-y-16">
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?= $childName !== 'footer-copyright' ? $block->getBlockHtml($childName) : '' ?>
            <?php endforeach; ?>
        </div>
    </div>

        <div class="container mt-16 w-full md:w-2/3 py-6 mx-auto flex items-center sm:flex-row flex-col">
            <div class="w-full md:text-left wd:w-1/2 text-center">
            <p>
                <?= $block->getChildHtml('copyright') ?>
            </p>
            </div>
            <div class="w-full text-center md:w-1/2 md:text-right">
                <img src="https://marytylor.com/media/wysiwyg/payment22.png" alt="accept payment" width="197" height="20" style="display: inline-block;">
            </div>
        </div>
</div>

