<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Media;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$mediaUrl = $viewModels->require(Media::class)->getMediaUrl();
?>
<div class="max-w-full md:max-w-6xl md:m-auto mx-auto">
    <div class="flex flex-wrap">
        <div class="w-full md:w-1/2 box1 mx-auto">
            <div class="p-4">
                <div class="img">
                    <img class="mx-auto" src="<?= $escaper->escapeUrl($mediaUrl . 'wysiwyg/small-icon-img-001.png') ?>" alt="">
                </div>
            </div>
        </div>
        <div class="w-full md:w-1/2 box2 mx-auto">
            <div class="p-4">
                <div class="img">
                    <img class="mx-auto" src="<?= $escaper->escapeUrl($mediaUrl . 'wysiwyg/small-icon-img-002.png') ?>" alt="">
                </div>
            </div>
        </div>
        <div class="w-full md:w-1/2 box2 mx-auto">
            <div class="p-4">
                <div class="img">
                    <img class="mx-auto" src="<?= $escaper->escapeUrl($mediaUrl . 'wysiwyg/small-icon-image-003.png') ?>" alt="">
                </div>
            </div>
        </div>
        <div class="w-full md:w-1/2 box2 mx-auto">
            <div class="p-4">
                <div class="img">
                    <img class="mx-auto" src="<?= $escaper->escapeUrl($mediaUrl . 'wysiwyg/small-icon-image-004.png') ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
