<div class="pb-4 md:pb-0 bg-white mt-7 relative">
    <img class="w-full" src="https://marytylor.com/cdn-cgi/image/quality=50/media/wysiwyg/05-handsoap-banner-mary-tylor-naturals.png" />
    <div class="w-full absolute top-0 md:top-24">
        <div class="w-full md:w-1/2 lg:w-1/3 pt-5 float-right">
            <div>
                <div class="text float-right">
                    <h5 class="text-neutral-700 font-light md:text-3xl text-2xl m-0">Organic<span class="text-lime-600"> products</span></h5>
                    <h1 class="md:text-4xl lg:text-6xl text-2xl font-bold text-zinc-800 my-4">Strawberry</h1>
                    <h2 class="items-center gap-x-3 my-6 hidden lg:flex">
                        <img src="https://marytylor.com/cdn-cgi/image/quality=50/media/wysiwyg/before_h2.png" class="relative left-0">
                        <span class="relative text-lg md:text-4xl text-lime-600 uppercase">Buy 1 get 1 free</span>
                    </h2>


                    <p class="my-6 text-lg text-stone-500 block hidden lg:block">Typi non habent claritatem insitam, est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.</p>
                    <div class="relative top-0">

                        <a class="w-40 btn justify-center hover:bg-gradient-to-bl text-sm mr-auto bg-gradient-to-br from-lime-600 to-lime-500" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" width="24" height="24" aria-hidden="true">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path>
                            </svg>
                            <span class="ml-2 inline md:ml-0 lg:ml-2">
                                Shop Now
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
