<?php
/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */
/**
 * @var $block \Mageside\Recipe\Block\Frontend\Recipe\RecipeList
 */
$config = $this->helper(\Mageside\Recipe\Helper\Config::class);
?>
<?php if ($config->getShowOnProductPage() && $block->getCollectionSize()) : ?>
    <strong><?= $config->getProductBlockTitle(); ?></strong>
    <?= $block->getChildHtml('recipe_list'); ?>
<?php endif; ?>
