<?php
/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */
/** @var \Mageside\Recipe\Block\Frontend\Recipe\Review $block */
/**
 * @var \Mageside\Recipe\Helper\Config $config
 */
$config = $this->helper(\Mageside\Recipe\Helper\Config::class);
?>
<?php $url = '#reviews'; ?>
<?php $urlForm = '#review-form'; ?>
<?php if ($config->getReviewEnabled()) : ?>
<?php if ($block->getReviewsSize()) : ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?php echo !$rating ? ' no-rating' : ''?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <?php if ($rating) :?>
        <div class="rating-summary">
             <span class="label"><span><?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Rating')) ?>:</span></span>
             <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $block->escapeHtml($rating); ?>%">
                 <span style="width:<?php /* @escapeNotVerified */ echo $block->escapeHtml($rating); ?>%">
                     <span>
                         <span itemprop="ratingValue">
                                <?php /* @escapeNotVerified */ echo $block->escapeHtml($rating); ?>
                         </span>% of <span itemprop="bestRating">100</span>
                     </span>
                 </span>
             </div>
         </div>
        <?php endif;?>
        <div class="reviews-actions">
                <span itemprop="reviewCount">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getReviewsSize()) ?>
                </span>&nbsp;
                <span>
                    <?php /* @escapeNotVerified */ echo($block->getReviewsSize() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?>
                </span>
        </div>
    </div>
<?php elseif ($block->getReviewsSize() == 0) : ?>
    <div class="product-reviews-summary empty">
        <div class="reviews-actions">
            <a class="action add" href="<?php /* @escapeNotVerified */ echo $block->escapeHtml($urlForm); ?>">
                <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Be the first to review this recipe')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
<?php endif; ?>
