<?php

/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */
/**
 * @var Mageside\Recipe\Block\Frontend\Recipe\RecipeList $block
 * @var Mageside\Recipe\Helper\Config $config
 */
$recipeCollection = $block->getAvailableRecipeCollection();
$config = $this->helper(\Mageside\Recipe\Helper\Config::class);
$imageHelper = $this->helper(\Mageside\Recipe\Helper\Image::class);
?>
<?php if (count($recipeCollection) == 0) : ?>
    <div class="page-title-wrapper">
        <h1 class="page-title">
            <span class="base">
                <?php echo $block->escapeHtml(__("Recipes not found")); ?>
            </span>
        </h1>
    </div>
<?php else : ?>
    <?php foreach ($recipeCollection as $recipe) : ?>
        <?php $recipeUrl = $block->getUrl($config->getSeoRoute()) . $recipe->getUrlKey() . $config->getSeoPostfix(); ?>
        <li>
            <div class="max-w-2xl mx-4 sm:max-w-sm md:max-w-sm lg:max-w-sm xl:max-w-sm sm:mx-auto md:mx-auto lg:mx-auto xl:mx-auto mt-16 bg-white shadow-xl rounded-lg text-gray-900">
                <div class="rounded-t-lg h-50 overflow-hidden">
                    <a class="recipe-item-photo" href="<?php echo $block->escapeHtml($recipeUrl) ?>">
                        <?php if ($recipe->getThumbnail()) : ?>
                            <img class="object-cover object-top w-full " src="<?php echo $block->escapeHtml($imageHelper->getResizedImage(
                                                                                    $block->getRecipeThumbnail($recipe->getThumbnail()),
                                                                                    'recipe_listing_image_thumbnail'
                                                                                )); ?>" alt="<?php echo $block->escapeHtml($recipe->getTitle()) ?>" title="<?php echo $block->escapeHtml($recipe->getTitle()) ?>">
                        <?php else : ?>
                            <img class="object-cover object-top w-full " src="<?php echo $block->escapeHtml($imageHelper->getResizedImage(
                                                                                    $block->getImageStub(),
                                                                                    'recipe_listing_image_thumbnail'
                                                                                )); ?>" alt="<?php $block->escapeHtml(__('Recipe Image')); ?>">
                        <?php endif; ?>
                    </a>
                </div>
                <div class="text-center mt-2">
                    <h2 class="font-semibold p-2">
                        <a class="line-clamp-1" href="<?php echo $block->escapeHtml($recipeUrl) ?>" title="<?php echo $block->escapeHtml($recipe->getTitle()); ?>">
                            <?php echo $block->escapeHtml($recipe->getTitle()); ?>
                        </a>
                    </h2>
                </div>
                <ul class="py-4 mt-2 text-gray-700 flex items-center justify-around">
                    <li class="flex flex-col items-center justify-around">
                        <img class="w-10 fill-current text-blue-900" src="<?php echo $block->escapeHtml($block->getViewFileUrl('Mageside_Recipe::images/recipe/serving.png')); ?>" title="<?php echo $block->escapeHtml(__('Servings Number')) ?>" width="35" height="35">
                        <?php $servingsNumber = $block->getFormatServingsNumber($recipe->getServingsNumber()); ?>

                        <div><?php echo $block->escapeHtml($servingsNumber . ' ' . (($servingsNumber == '1')
                                    ? __('person') : __('people'))); ?></div>
                    </li>
                    <li class="flex flex-col items-center justify-between">
                        <img class="w-10 fill-current text-blue-900" src="<?php echo $block->escapeHtml($block->getViewFileUrl('Mageside_Recipe::images/recipe/prep-time.png')); ?>" title="<?php echo $block->escapeHtml(__('Prep Time')) ?>" width="35" height="35">

                        <div><?php echo $block->escapeHtml($block->getFormatCookTime($recipe->getPrepTime())); ?></div>
                    </li>
                    <li class="flex flex-col items-center justify-around">
                        <img class="w-10 fill-current text-blue-900" src="<?php echo $block->escapeHtml($block->getViewFileUrl('Mageside_Recipe::images/recipe/cooking-time.png')); ?>" title="<?php echo $block->escapeHtml(__('Cooking Time')) ?>" width="35" height="35">

                        <div><?php echo $block->escapeHtml($block->getFormatCookTime($recipe->getCookTime())); ?></div>
                    </li>
                </ul>
                <div class="p-4 border-t mx-8 mt-2">
                    <a href="<?php echo $block->escapeHtml($recipeUrl) ?>" class="w-full lg:w-1/2  text-center block mx-auto rounded-full bg-gray-900 hover:shadow-lg font-semibold text-white px-6 py-2">Follow</a>
                </div>
            </div>
        </li>
    <?php endforeach ?>
<?php endif; ?>
