<?php
/**
 * Copyright © Mageside, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Mageside\Recipe\Block\Frontend\Recipe\Recipe */ ?>
    <div class="text-center md:w-1/3 w-full mx-auto my-3">
        <a class="btn btn-primary block font-bold" href="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getPrintUrl()) ?>" target="_blank" ><span><?= /* @escapeNotVerified */ __('Print recipe')  ?></span></a>
    </div>
<?= $block->getChildHtml() ?>

