<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $width = (int)$block->getBackgroundImageWidth() ?: 1000;
    $imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>

<?php
    $_postCollection = $block->getPostCollection();
    $count = (int) $_postCollection->count();
    $owlCarouselCss = $block->getViewFileUrl("Magefan_BlogExtra::css/owl.carousel.min.css");
    $owlCarouselCssDefault = $block->getViewFileUrl("Magefan_BlogExtra::css/owl.theme.default.min.css");
?>

<?php if ($count) { ?>
<div class="mfblog-post-carousel block related">
    <div class="block-title">
        <?php if ($block->getTitle()) { ?>
            <strong><?= $block->escapeHtml($block->getTitle()) ?></strong>
        <?php } else { ?>
            <strong><?= $block->escapeHtml(__('Related Posts')) ?></strong>
        <?php } ?>
    </div>
    <div class="block-content">
        <div class="post-items owl-carousel owl-theme owl-blog-post">
            <?php foreach ($_postCollection as $_post) { ?>
                <?php
                    $_postUrl = $block->escapeUrl($_post->getPostUrl());
                    $_postName = $block->escapeHtml($_post->getTitle());
                ?>
                <div class="post-item">
                    <!-- post item -->
                    <div class="block-post">
                        <!-- img container -->
                        <div class="image-container">
                            <!-- post image -->
                            <a class="image-wrap _4x3" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                <?php
                                $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                if ($featuredImage) {
                                    $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                    $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                    if (!$featuredImgAlt) {
                                        $featuredImgAlt = $_postName;
                                    }
                                } else {
                                    $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/samples/' . rand(1, 8) . '.jpeg');
                                    $featuredImgAlt  = '';
                                }
                                ?>
                                <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                            </a>
                        </div>

                        <!-- block info -->
                        <div class="post-info">
                            <!-- post title -->
                            <div class="post-title-wrap mb-1">
                                <h3 class="post-title m-0">
                                    <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!-- end post item -->
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<script>
    require(['jquery', 'domReady!'], function($){
        if (!$(".owl-carousel")) return;

        /* Deferer owl.carousel css loading */
        $("head").append(
            $("<link rel='stylesheet' href='<?= $block->escapeUrl($owlCarouselCss) ?>' type='text/css' media='screen' />")
        );
        $("head").append(
            $("<link rel='stylesheet' href='<?= $block->escapeUrl($owlCarouselCssDefault) ?>' type='text/css' media='screen' />")
        );

        /* Deferer owl.carousel js loading */
        require(['Magefan_BlogExtra/js/owl.carousel'], function(){
            $(".owl-carousel").owlCarousel({
                nav : true,
                navText : "",
                loop : false,
                dots : false,
                autoPlay: false,
                items : 4,
                margin : 35,
                responsive : {
                    0 :{
                        items: 1
                    },
                    768 :{
                        items: 3
                    },
                    1000 :{
                        items: 4
                    }
                }
            });
        });
    });
</script>
<?php } ?>