<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Review\Block\Form;
use Hyva\Theme\ViewModel\ReCaptcha;

//phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Form $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

$formId = 'review_form';

/** @var GraphqlViewModel $gqlViewModel */
$gqlViewModel = $viewModels->require(GraphqlViewModel::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on Magento_ReCaptchaReview module
/** @var ReCaptcha $recaptcha */

?>
<div class="mx-auto py-6 items-center" id="review-form" tabindex="-1">
    <div class="card w-full px-6 py-3">
        <div class="text-xl my-3">
            <?= $escaper->escapeHtml(__('Write Your Own Review')) ?>
        </div>
        <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form class="review-form"
                  @submit.prevent="submitFormReview()"
                  id="<?= $escaper->escapeHtmlAttr($formId) ?>"
                  action="<?= $block->getAction(); ?>"
                  x-data="initReviewForm()"
                  x-defer="intersect"
            >
                <?= $block->getBlockHtml('formkey') ?>

                <fieldset>
                    <legend class="text-xs">
                        <span>
                            <?= $escaper->escapeHtml(
                                __("You're reviewing:")
                            ) ?>
                        </span>
                        <span class="font-semibold">
                            <?= $escaper->escapeHtml($block->getProductInfo()->getName()) ?>
                        </span>
                    </legend>

                    <div>
                        <div>
                            <label for="nickname_field" class="sr-only">
                                <span><?= $escaper->escapeHtml(__('Nickname')) ?></span>
                            </label>
                            <div>
                                <input class="form-input mt-3 block w-full text-sm"
                                       required
                                       placeholder="<?= $escaper->escapeHtmlAttr(__('Nickname') . '*') ?>" type="text"
                                       name="nickname" id="nickname_field"/>
                            </div>
                        </div>
                        <div>
                            <label for="summary_field" class="sr-only">
                                <span><?= $escaper->escapeHtml(__('Summary')) ?></span>
                            </label>
                            <div>
                                <input class="form-input mt-3 block w-full text-sm"
                                       required
                                       placeholder="<?= $escaper->escapeHtml(__('Summary') . '*') ?>" type="text"
                                       name="title"
                                       id="summary_field"/>
                            </div>
                        </div>
                        <div>
                            <label for="review_field" class="sr-only">
                                <span><?= $escaper->escapeHtml(__('Review')) ?></span>
                            </label>
                            <div>
                            <textarea class="form-input mt-3 block w-full text-sm"
                                      required
                                      placeholder="<?= $escaper->escapeHtml(__('Review') . '*') ?>" name="detail"
                                      id="review_field" cols="5"
                                      rows="3"></textarea>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <br>
                <?= $block->getBlockHtml('recaptcha_input_field_recaptcha') ?>
                <div class="my-3">
                    <div class="relative inline-block">
                        <button x-show="!displaySuccessMessage" type="submit" class="btn btn-primary flex items-center">
                            <span><?= $escaper->escapeHtml(__('Submit Review')) ?></span>
                            <span x-show="isLoading" x-cloak class="ml-2">
                <?= $hyvaicons->loaderHtml('text-primary', 20, 20); ?>
            </span>
                        </button>
                        <p x-show="displaySuccessMessage" x-cloak class="text-green flex items-center">
                            <span class="inline-block w-8 h-8 mr-3">
                                <?= $heroicons->checkCircleHtml(); ?>
                            </span>
                            <?= $escaper->escapeHtml(__('You submitted your review for moderation.')) ?>
                        </p>
                        <template x-if="displayErrorMessage">
                            <p class="text-red flex items-center">
                <span class="inline-block w-8 h-8 mr-3">
                    <?= $heroicons->exclamationCircleHtml(); ?>
                </span>
                                <template x-for="errorMessage in errorMessages">
                                    <span x-html="errorMessage"></span>
                                </template>
                            </p>
                        </template>
                    </div>
                    <?= $block->getChildHtml('form_additional_after') ?>

                </div>
            </form>

            <script>
                function initReviewForm() {

                    return {
                        isLoading: false,
                        displayNickname: false,
                        displaySuccessMessage: false,
                        displayErrorMessage: false,
                        errorMessages: [],
                        errors: 0,
                        hasCaptchaToken: 0,
                        nickname: null,
                        summary: null,
                        ratings: [],
                        review: null,
                        setErrorMessages: function (messages) {
                            this.errorMessages = [messages]
                            this.displayErrorMessage = this.errorMessages.length
                        },
                        submitFormReview: function () {
                            // Do not remove $form. The variable is used in the recaptcha child template.
                            const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');

                            <?= $block->getChildHtml('recaptcha_validation'); ?>
                            if (this.errors === 0) {
                                $form.submit();
                            }
                        }
                    }
                }
            </script>
        <?php else: ?>
            <div
                id="review-form"
                tabindex="-1"
            >
                <div class="pb-6">
                    <?= $escaper->escapeHtml(
                        __(
                            'Only registered users can write reviews. Please <a href="%1" class="underline">Sign in</a> or <a href="%2" class="underline">create an account</a>',
                            $block->getLoginLink(),
                            $block->getRegisterUrl()
                        ),
                        ['a']
                    ) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
